max_epochs: 400
gpus: "0"
fast_dev_run: false
profiler: False
reload_dataloaders_every_epoch: true
# overfit_batches: 1
# lr: 0.005
# accelerator: "dp"
# metric: ${metric.metric_name}
# weights_summary: top
# accumulate_grad_batches: 1
# log_every_n_steps: 100
# num_sanity_val_steps: 0
#gradient_clip_val: 0.0
